### ISSUE TITLE
Next release 

### ISSUE THREAD

**Issue by La0** [getsentry/pytest-responses#25]
Hey, thanks for maintaining this awesome tool.

Do you have any idea when the next release might happen ? The [fix for distutils warnings](https://github.com/getsentry/pytest-responses/commit/ce7a6e00c15b6073b1eaa4ff9d71a5cbd7a91a4a) would be really useful to have in an official version. :+1:

**Comment by PixelStroke** [comment]
+1 On this as well. Any reason this isn't already available?

**Comment by markstory** [comment]
Looks like a release was attempted a while back but didn't succeed. I'll try running another release.

**Comment by yschneiderTEKLIA** [comment]
Hey! I'm super interested in this as well. Any update?

**Comment by markstory** [comment]
The subsequent release also failed. @getsentry/open-source or @getsentry/dev-infra are familiar with this error?

**Comment by asottile-sentry** [comment]
hmmm weird, that error usually occurs only if there are either (1) no tags or (2) the clone is shallow -- but it doesn't look like either of those should apply here :thinking:

**Comment by asottile-sentry** [comment]
oh yes - the `fetch-depth: 0` was added after the release -- you should be able to try again and it'll work @markstory

**Comment by La0** [comment]
Thanks guys !
