### ISSUE TITLE
Incompatibilty with Pytest 4.1.0

### ISSUE THREAD

**Issue by jakul** [getsentry/pytest-responses#8]
```
item = <TestCaseFunction test_get_events_by_policy>
    def pytest_runtest_setup(item):
>       if not item.get_marker('withoutresponses'):
E       AttributeError: 'TestCaseFunction' object has no attribute 'get_marker'
../../../.cache/tox/app/lib/python3.6/site-packages/pytest_responses.py:8: AttributeError
```

`get_marker` has been removed  in pytest 4.1.0The pytest changelog suggests using `get_closest_marker` instead.

https://docs.pytest.org/en/latest/changelog.html

**Comment by mixja** [comment]
This should be fixed by https://github.com/getsentry/pytest-responses/pull/7

**Comment by jakul** [comment]
@dcramer Does this PR look ok to you?

**Comment by wesleykendall** [comment]
@dcramer can https://github.com/getsentry/pytest-responses/pull/9 be released? Should be able to close this issue

**Comment by dcramer** [comment]
Pushing out 0.4.0
